### ISSUE TITLE
Depend only on `libclang`, not also on `llvm` 

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#102]
In https://github.com/well-typed/hs-bindgen/pull/100 we changed things so that we depend on `llvm` to figure out where `libclang` is (as it does not support `pkg-config`). This works, but requires a larger installation than strictly necessary. Perhaps we could additionally provide an alternative way to configure `libclang` that does not require `llvm`.

**Comment by phadej** [comment]
![libclang](https://github.com/user-attachments/assets/61e62f5b-fa99-454b-9288-e7ab259b44db)

![libclang](https://github.com/user-attachments/assets/21a35614-05f9-4a6a-85c5-5acd950ce7b0)

- libclang1-14 (https://packages.debian.org/bookworm/libclang1-14) depends on
  libllvm14 (https://packages.debian.org/bookworm/libllvm14)

- llvm-14 (https://packages.debian.org/bookworm/llvm-14) also depends on 
  libllvm14 (https://packages.debian.org/bookworm/libllvm14)
- and only few extra things (z3, pfm, ncurses). Z3 is probably the only one
  usually not found on machines, but it's quite small.

That said, I think `llvm` is often there already, either for GHC backend (even if not used 100% of the time),
or `clang` the C compiler.

So the installation is not *that much* larger. TL:DR `libclang` depends on `libllvm`. `llvm` on few other (small) things, but too many.

**Comment by edsko** [comment]
Fair enough. Will mark as low priority.
