### ISSUE TITLE
llvm-config doesn't exist on Windows

### ISSUE THREAD

**Issue by phadej** [well-typed/hs-bindgen#117]
I found this https://stackoverflow.com/questions/17096804/where-is-llvm-config-in-windows and that https://discourse.llvm.org/t/no-llvm-config-exe-or-llvmconfig-cmake-in-pre-built-windows/57692/3, and apparently that is at least true for LLVM-14 still.

Do we need to support Windows?

**Comment by phadej** [comment]
https://github.com/well-typed/hs-bindgen/pull/116 solves adds macOS CI setup, but windows CI is stuck on a decision.

If we need to support Windows than #102 is worth solving, but for this reason, not the minimal installation. I doubt anyone cares about minimal `libclang` installation on Windows, the official bindist is probably the preferred. (Or maybe you can use `rustup` installation too, at least on Ubuntu `rust` depends on `libllvm`, so you kind of get most of the stuff there already; but you probably miss development headers, which may be included on Windows).

**Comment by edsko** [comment]
@phadej The decision right now is that we should try and support Windows, and reconsider if we come across some major obstacles. So yes, let's try to make Windows work.
