### ISSUE TITLE
Don't use String

### ISSUE THREAD

**Issue by phadej** [well-typed/hs-bindgen#142]
We use String for names, not great.

I think `ShortText` is better. I don't think there can be identifiers which are not valid text. But we can also use `ShortByteString` to be sure.

That said, I think having a `newtype Name` would help separate names from everything else. (In particular `Name`s is something we will need to mangle as lexically C and Haskell are different)

**Comment by edsko** [comment]
Putting some basic infra in place for this, but will defer name mangling to a separate ticket #189.
