### ISSUE TITLE
Name mangling scheme

### ISSUE THREAD

**Issue by phadej** [well-typed/hs-bindgen#160]
```haskell
instance Storable primitive where ...
```

is invalid. Similarly `data Foo = Foo { Bar :: Int }` would be invalid.

We need a name mangling scheme for at least data type names and field names

See example outputs in `master` or #159

**Comment by TravisCardwell** [comment]
I just discovered this issue.  #189 is a duplicate, but I am closing this issue in favor of #189 because it has discussion.

In #189, I replied:

> I see that the case of the first letter is already causing problems.  I will fix this ASAP, before adding the context and options or working on edge cases.
