### ISSUE TITLE
Implement platform-specific end-of-line characters

### ISSUE THREAD

**Issue by TravisCardwell** [well-typed/hs-bindgen#211]
In the preprocessor execution mode, users may want to view the generated source code.  Should we take care to implement platform-specific end-of-line characters in the generated source code?

Reference:

* Wikipedia: [Newline](https://en.wikipedia.org/wiki/Newline)

**Comment by phadej** [comment]
No. Windows machine can handle `\n`. `\r\n` is abomination.
