### ISSUE TITLE
Name mangling: preserve leading and trailing underscores

### ISSUE THREAD

**Issue by TravisCardwell** [well-typed/hs-bindgen#312]
We shall assume that leading and trailing underscores have special meaning, while underscores in between letters/numbers are just used for separation.  Multiple leading/trailing underscores should be preserved.

Haskell identifiers that start with a lowercase letter may start with an underscore.

Haskell identifiers that start with an uppercase letter may *not* start with an underscore.  For example, translating C type `_foo` to a Haskell type constructor that preserves the leading underscore requires a prefix before the underscore.

@phadej provided an example in #306:

```c
typedef struct _linked_list {
  int x;
  struct _linked_list* next; /* linked_list doesn't exist here yet */
} linked_list;
```

```haskell
data C_LinkedList = MkC_LinkedList { x :: Int, next :: Ptr C_LinkedList }
newtype CLinkedList = MkCLinkedList C_LinkedList
```

Note that `joinWithCamelCase` is still used, so leading and trailing underscores should be handled separately.

**Comment by phadej** [comment]
IMHO, the default name mangling should do as little as necessary to make valid Haskell names.

Doing underscores to camelCase like translations feels a bit tricky. Perfectly we will be able to describe the mangling rules in few sentences. Users should be able to predict what the Haskell names will be. IMHO it doesn't matter what are the "idiomatic" names in Haskell.

In particular, recently I started to dislike the `C` prefix. Why we have it.

**Comment by TravisCardwell** [comment]
This is a question for @edsko, but I think it is just a matter of taste/preference.

A few technical notes:

* A prefix is required for type constructors to preserve leading underscores without translation or escaping, since type constructor names may not start with an underscore.

* When preserving C names as much as possible, a prefix makes it possible to avoid converting the case of the first letter of the C name.
