### ISSUE TITLE
Support fixed-sized arrays in low-level bindings

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#36]
We should implement an (optional) mechanism for encoding the size of a statically sized array in the Haskell type, perhaps [Data.Vector.Storable.Sized](https://hackage.haskell.org/package/vector-sized-1.6.1/docs/Data-Vector-Storable-Sized.html#t:Vector) or a bespoke

```haskell
newtype ArrayPtr (n :: Nat) a = ArrayPtr (Ptr a)
```

Tracking support for multidimensional arrays as a separate ticket at https://github.com/well-typed/hs-bindgen/issues/59.

**Comment by phadej** [comment]
Note that in structs fixed sized arrays are "spliced in", they are not pointers.

**Comment by edsko** [comment]
This is implemented (`ConstantArray`).
