### ISSUE TITLE
Automatically discover location of `libclang`

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#78]
Unfortunately, `libclang` does not support `pkg-config` (https://github.com/llvm/llvm-project/issues/9777). [`clang-pure`](https://hackage.haskell.org/package/clang-pure) uses a [custom setup script](https://hackage.haskell.org/package/clang-pure-0.2.0.6/src/Setup.hs) which calls [`llvm-config`](https://llvm.org/docs/CommandGuide/llvm-config.html), we might consider doing something similar. For now, we simply depend on something like this in `cabal.project`:

```
package hs-bindgen
  extra-lib-dirs:
    /usr/lib/llvm-18/lib
  extra-include-dirs:
    /usr/lib/llvm-18/include
```

**Comment by edsko** [comment]
Not sure if we should use a custom `Setup.hs` script here, or make use of the [new `Hooks` API](https://sheaf.github.io/cabal-talk/docs/Cabal-hooks/Distribution-Simple-SetupHooks.html). 

For more information on the new Hooks API, see [@sheaf 's talk](https://sheaf.github.io/cabal-talk/) and the corresponding [examples](https://github.com/sheaf/cabal-talk/tree/master/examples/hooks).

**Comment by phadej** [comment]
`build-type: Configure`.
