### ISSUE TITLE
Deal with file encodings

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#87]
We are currently assuming everything is ASCII, but that might not always be the case? (UTF-8 for `struct` field names, for example?)

**Comment by phadej** [comment]
The standard talks about "basic character set", which is quite limited set of characters. I think the further encodings are mostly interesting for comments. Those can be anything in C (AFAIK, after all they are ignored by compiler), but we probably want Haskell code to be UTF-8.

**Comment by edsko** [comment]
I _think_ `(lib)clang` internally deals only with UTF-8; for example, the [Python bindings](https://libclang.readthedocs.io/en/latest/_modules/clang/cindex.html) have this comment

```python
    # Python 3 strings are unicode, translate them to/from utf8 for C-interop.
```

and the [`libclang` lexer](https://github.com/llvm/llvm-project/blob/main/clang/lib/Lex/Lexer.cpp#L4442) assumes UTF-8 also. It would be good to find an authoritative reference to confirm this, but so far I have not found any.

**Comment by phadej** [comment]
Unrelatedly, what on earth does "Python 3 strings are unicode" mean. I was curious, and the answer seems to be https://peps.python.org/pep-0393/ - TL;DR there are no single fixed internal representation.

**Comment by edsko** [comment]
`libclang` uses UTF-8, and we're testing that we deal with this correctly. Other file encodings seem less relevant, we can reopen a ticket if and when we need to.
