### ISSUE TITLE
Pipeline setup is inflexible

### ISSUE THREAD

**Issue by phadej** [well-typed/hs-bindgen#99]
Why dump is a separate pipeline? It's useful to be able to do "the stuff" but also dump *various* intermediate data (c.f. GHC `-ddump-*` flags. Also `hs-bindgen` should strive to be better as a library (than e.g. `ghc`), so one can test pieces of the pipeline (c.f. GHC is essentially tested by only running the whole program: that works, but there are more moving pieces in tests where there don't need to be).

**Comment by phadej** [comment]
In particular, I'd imagine that Template Haskell users would prefer using some structured approach for configuration (and also wanting to dump stuff for debug purposes). I don't see how current `Spec` would make that possible.

**Comment by edsko** [comment]
I absolutely agree that `hs-bindgen` should be usable as a library, that's partly why I introduced this `Spec` in the first place. Indeed, I imagine that the high-level API, in cases where a lot of customization is required, this will be done by using `hs-bindgen` as a library (https://github.com/well-typed/hs-bindgen/issues/21). But the current `Spec` is only a first version, certainly not wedded to the precise way it's currently formulated. Do you have specific suggestions? We could of course add dump flags, but that feels quite stringy; part of the purpose of this sketch of `Spec` was that it was typed.

As regards TH, I wasn't imagining that TH code would use `Spec` directly, although I suppose it could. Perhaps there is actually some code in the command line parser that should not live there, but should instead be moved to the library as a set of functions to construct common `Spec` scenarios.

**Comment by edsko** [comment]
Would it be better if we had a single datatype with commands for the various phases? Or just forego the whole thing and just expose a set of functions instead?

**Comment by phadej** [comment]
> but that feels quite stringy

Sure, but having a data-type representing multiple outputs is not-obvious to me

> Or just forego the whole thing and just expose a set of functions instead?

I would start with that. Assembling the pipeline manually (and storing / displaying / ... intermediate results as needed) is at least simple.

Then when we know the structure more we might see a way to abstract over it.

That said, I'd still see a value in `data Args` (true *data* type which you can `Show`) which is the result of command line parser, and that is then interpreted to construct the pipeline. Technically one could fuse `Args` away, but in practice I find showable values quite useful to have.

**Comment by edsko** [comment]
Agreed on having something `Show`able. `Spec` used to be, until I added the `Tracer`. Maybe that should move out, if we keep `Spec` at all.

**Comment by phadej** [comment]
Perfectly, each building block function takes own `Tracer`, e.g. `parseFile :: Tracer IO ParseTrace -> ... -> IO ...`, and then the user passes needed `Tracer`s in, so they have control on what is traced at the end. (The current setup with levels e.g. is more like traditional logging framework, not really using `Tracer` abstraction full potential).

**Comment by edsko** [comment]
Yeah, agreed. That's another thing that removing `Spec` would make easier. Ok, let's just get rid of it for now, and then focus on having a very clean API.

**Comment by edsko** [comment]
I'll make the change.
